spring:
  application:
    name: notification-service

server:
  port: 8083

#messaging configuration
spring:
  rabbitmq:
    host: localhost
    port:5672
    username: guest
    password: guest

#other service specific configuration
notification:
  message: "welcome to the notification service!"
