spring:
  application:
    name: user-service
    
  datasource:
    url: jdbc:mysql://localhost:3306/movie
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
  profiles:
    active: dev

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG


